version: '3'

services:
  nginx:
    image: emcniece/nginx-cache-purge:latest
    volumes:
      - ./images:/usr/share/nginx/images/
      - ./cache:/data/nginx/cache/
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '80:80'
