version: '3'

services:
  nginx:
    image: firesh/nginx-lua:latest
    volumes:
      - ./images:/usr/share/nginx/images/
      - ./cache:/data/nginx/cache/
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./sripts.lua:/etc/nginx/sripts.lua
    ports:
      - '80:80'
